name: SeshRecap
options:
  bundleIdPrefix: com.seshrecap
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  groupSortPosition: top
  generateEmptyDirectories: true

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    SWIFT_VERSION: "5.9"

configs:
  Debug:
    settings:
      DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
  Release:
    settings:
      DEBUG_INFORMATION_FORMAT: dwarf-with-dsym

targets:
  SeshRecap:
    type: application
    platform: iOS
    sources:
      - path: SeshRecap
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        INFOPLIST_FILE: SeshRecap/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.seshrecap.app
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: YES
        LD_RUNPATH_SEARCH_PATHS: $(inherited) @executable_path/Frameworks
        XCCONFIG_FILE: $(SRCROOT)/SeshRecap/Config/Secrets.xcconfig
    dependencies:
      - package: supabase-swift
        product: Supabase
      - package: RevenueCat
        product: RevenueCat
    # Entitlements disabled - requires paid Apple Developer account
    # entitlements:
    #   path: SeshRecap/SeshRecap.entitlements
    #   properties:
    #     com.apple.developer.applesignin:
    #       - Default
    #     aps-environment: development

packages:
  supabase-swift:
    url: https://github.com/supabase/supabase-swift
    from: "2.0.0"
  RevenueCat:
    url: https://github.com/RevenueCat/purchases-ios
    from: "4.0.0"

schemes:
  SeshRecap:
    build:
      targets:
        SeshRecap: all
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
